### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by ziyiyin97** [cmgcds/fastvpinns#17]
First of all, I sincerely apologize for my late reviews. I encountered some unforeseeable issues recently, which delayed my response to your manuscript. Thank you again for understanding.

Overall, it is an awesome software package dedicated to hp-VPINNs. The statement of need is clear and well-motivated to me. The tutorials are helpful and the API documents are thorough.

The only concerns I have are:
1. #16 I believe the tutorial docs should be fixed this way but correct me if wrong
2. One of the claims in the manuscript is that this package can read external mesh from a `.mesh` file. This is substantiated in the tutorial scripts as they indeed load mesh from a `.mesh` file. However, it is not so clear how a `.mesh` file is generated from GMSH package. I suggest a short tutorial script on how to generate a `.mesh` file from a user-defined mesh, especially one that is slightly more "complicated" or "arbitrary" than uniform mesh or circular mesh. With this tutorial, one could examine the applicability of this package to more realistic problems at hand where the mesh is somehow irregular.

**Comment by divijghose** [comment]
Hello @ziyiyin97, 
Thank you for your review of our work. We have tried to address the concerns you have raised as follows:
1. The minor errors in documentations have been fixed by merging your changes #16  into main. 
2. We have added two tutorials on your documentation site that deal with mesh generation using Gmsh. One deals with [mesh generation using external CAD files](https://cmgcds.github.io/fastvpinns/_rst/tutorials/mesh_generation/mesh.html) and the other with [mesh generation from GEO files](https://cmgcds.github.io/fastvpinns/_rst/tutorials/mesh_generation/mesh.html#creating-the-geometry-in-geo-file). With these tutorials, a user should be able to leverage the external mesh capabilities of FastVPINNs. 
![image](https://github.com/user-attachments/assets/77d39d4e-0e56-47cf-84c2-4d4442fb26a5)


If you are satisfied with these changes, I can close this issue and you can do the needful for the JOSS review. If not, do get back to us.

**Comment by ziyiyin97** [comment]
I think these changes are great!
